<?php
	$link = mysqli_connect(/*CREDENTIALS*/);
	if (mysqli_connect_errno($link)) {
		echo "Failed to connect to MySQL: " . mysqli_connect_error();
	}

	$name = $_POST['theme'];
	$an_pt = trim(ereg_replace("[^A-Za-z0-9]", "", $name));
	$request = "INSERT INTO plushthemes
	VALUES ('$an_pt');";

	$result = mysqli_query($link, $request) or die("Error adding $name: " . mysqli_error($link));
	echo "$an_pt added";

	?>
