<?php
	$link = mysqli_connect('','soundog_akrona','4dr1$N', 'soundog_neomonsters');
	if (mysqli_connect_errno($link)) {
		echo "Failed to connect to MySQL: " . mysqli_connect_error();
	}
	
	$name = $_POST['name'];
	
	$request = "DELETE
		FROM books
		WHERE name = '$name';";
		
	$result = mysqli_query($link, $request) or die("Error deleting $name: " . mysqli_error($link));
	echo "$name deleted";
	
	?>