<table><tr>
					<td>Image</td>
					<td>Name</td>
					<td>Rarity</td>
					<td>Value</td>
					<td>Theme</td></tr>

<?php

$link = mysqli_connect(/*CREDENTIALS*/);
		if (mysqli_connect_errno($link)) {
			echo "Failed to connect to MySQL: " . mysqli_connect_error();
			}

			$request = "SELECT *
			FROM food;";

			$result = mysqli_query($link, $request) or die("ERROR: " . mysqli_error($link));


			//too lazy to rename properly
			while ($line = mysqli_fetch_array($result, MYSQLI_ASSOC)){
				$name = $line['name'];
				$rarity = $line['rarity'];
				$value = $line['value'];
				$description = $line['description'];
				$imgurl = $line['imgurl'];
				$theme = $line['theme'];


				echo "<tr>
						<td><img src=" . $imgurl . ">
						<td>$name</td>
						<td>$rarity</td>
						<td>$value</td>
						<td>$theme</td> </tr>";
			}
?>
</table>
