<?php include("layout/header.txt"); ?>
	Okay this is gonna be an admin panel.
	<br>Things we need for an admin panel
	<ul>
	<li>Add Pet Species
	<li>Add Pet Color
	<li>Add Pet Type/UPLOAD. include alts. maybe have something that pops up and says 'hey your makin an alt'
	<li>Add Collectible Item
	<li>Add Paintbrush/Morphing Potion (w/ upload)
	<br>
	<li>Create Pet (no restrictions on owner/species/color/etc)
	<li>Create Item (no restrictions on owner)
	<li>Create Account
 	<br>
	<li>Delete Pet
	<li>Delete Item (have to be by user)
	<li>Delete Account
	<li>Clear Pet/Userlookup
	<br>
	<li>Modify User's NP Amount
	<li>Modify account information
	<li>Modify pet information
	<li>Modify Create-a-pet Restrictions
	<br>
	<li>View User's Inventory
	<li>View User's IP History
	<li>View Item Transfer History
	<li>View All Accounts
	<li>View Inactive Accounts
	<li>View Reported Neomails
	

	<br>
	<li>Open/Close Registration
	</ul>
	
	Oh btw make sure you change this to index.html
	
<?php include("layout/footer.txt"); ?>