<?php include("layout/header.txt");?>
<title>Minineo Games</title>

Welcome to the games room! It's really goddamn empty right now because games are actually kind of a pain to code. I need practice tho. So um. We'll get more later.

<br><br>For now we have these really lazy ones. 
<br><a href='/win_a_thing.phtml'>Win A Thing</a> - every hour you get a random item and some money.
<br><a href='/gambling.phtml'>Gamble money</a> - once a day you can either win or lose money! ~risky~

<?php include("layout/footer.txt");?>