<?php

		$link = mysqli_connect('','soundog_akrona','4dr1$N', 'soundog_neomonsters');
		if (mysqli_connect_errno($link)) {
			echo "Failed to connect to MySQL: " . mysqli_connect_error();
		}
	
		function pet_img($link, $species, $color, $alt, $pose){
		//people aren't interested in multiple poses right now, so we'll only be handling happy and circle.
		
		//if alt is set to 0, that means the image is hosted on Neopets' server.
		if($alt == 0){
			if($pose == 'circle'){
				$imgurl = "http://images.neopets.com/pets/" . $species . "_" . $color . "_baby.gif";				
			}
			else{
				$imgurl = "http://images.neopets.com/pets/happy/" . $species . "_" . $color . "_baby.gif";
			}
		}
		//otherwise, it is hosted on our own server.
		else{
				$imgurl = "/images/pets/" . $species . "_" . $color . "_baby";
				if($alt > 1){
					$imgurl .= "_" . $alt;
				}
				$imgurl .= ".gif";
		}
		return $imgurl;
	}
	
	$neo = pet_img($link, $jubjub, $blue, 0, $circle);
	echo "$neo";